services:
#1
    frontend:  
      build:
        context: .
        args:
          - REACT_APP_BACKEND_URL=http://localhost:8080
      ports:
        - "5000:5000"
#2
    backend:
      build:
        context: ../example-backend/.
      ports:
        - "8080:8080"
      environment: 
        - REQUEST_ORIGIN=http://localhost:5000
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
        - POSTGRES_PASSWORD=salasana
#3
    redis:
      image: redis
      restart: unless-stopped
#4
    db:
      image: postgres
      restart: unless-stopped
      container_name: tietokanta
      environment:
        - POSTGRES_PASSWORD=salasana



     