
FROM golang:1.16-alpine AS builder

# Use /usr/src/app as our workdir. The following instructions will be executed in this location.
WORKDIR /usr/src/app

RUN apk add build-base

COPY . .

RUN go build && \
        go test ./...

FROM scratch
FROM alpine
COPY --from=builder /usr/src/app/server /server

RUN adduser -D appuser
EXPOSE 8080

ENV REQUEST_ORIGIN=https://example.com

ENV PORT=8080

USER appuser

CMD ./server